optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.001,
    weight_decay: 0.0005
}}

scheduler: {
  type: CosLR,
  kwargs: {
}}

model: {
  part_num: 4,
  part_decoder: True,
}

train: {
  batch_size: 128,
  data_point: 2048,
  max_epoch: 1000,
  ckpt_save_freq: 200,
}